name: Playwright Tests

# Trigger tests on specific events
on:
  push:
    branches:
      - main # Run tests when code is pushed to the main branch
  pull_request: # Run tests on pull requests

jobs:
  test:
    runs-on: ubuntu-latest # The machine to run tests on (Linux)

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Setup Node.js (Install Node.js for running your tests)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18' # Use Node.js version 18

      # Step 3: Install dependencies
      - name: Install dependencies
        run: npm ci

      # Step 4: Run Playwright tests
      - name: Run Playwright Tests
        run: npx playwright test